[package]
name = "<<<program_name>>>"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "<<<program_name>>>"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true
panic = "unwind"
lto = false

[profile.release]
opt-level = 3
# If you need to use exec_panic hook, enable `unwind`
# panic = "unwind"
panic = "abort"
lto = true

[dependencies.mingling]
version = "0.4"
features = [
    "extras",
??? >>> ASYNC
    "async",
??? <<<
??? >>> PARSER_PICKER
    "picker",
??? <<<
??? >>> PARSER_CLAP
    "clap",
??? <<<
??? >>> PARSER_BUILTIN
    "parser",
??? <<<
??? >>> DISPATCH_TREE
    "dispatch_tree",
??? <<<
??? >>> PATHF
    "pathf",
??? <<<
??? >>> COMPLETION
    "comp",
??? <<<
??? >>> STRUCTURAL_RENDERER
    "structural_renderer",
??? <<<
]

??? >>> BUILD_TIME
[build-dependencies.mingling]
version = "0.4"
features = [
    "build",
??? >>> DISPATCH_TREE
    "dispatch_tree",
??? <<<
??? >>> PATHF
    "pathf",
??? <<<
??? >>> COMPLETION
    "comp",
??? <<<
]
??? <<<

[dependencies]
??? >>> PARSER_CLAP
clap = { version = "4", features = [ "derive" ] }
??? <<<
??? >>> TOKIO
tokio = { version = "1", features = [ "full" ] }
??? <<<
??? >>> ASYNC_STD
async-std = "1"
??? <<<
