# --------------------------------------------------------------------------- #
# 
#   Mingling 0.4 Template
#
# > Welcome to Mingling.
# > Before starting your project, please fill out this `checklist` file, 
# > as it will determine the structure of your project.
#
# --------------------------------------------------------------------------- #

### 1. Please enter your program name:

program_name = "my-cli"

### 2. Please select the parser used in the project,

# Clap Derive, the most mainstream option. 
# When enabled, 
# Mingling will use the struct implementing clap::Parser as the Entry Type
# ------------------
# parser = "clap"
# ------------------

# Builtin, Mingling's built-in argument parser, lightweight, order-sensitive, suitable for simple parsing
# ------------------
# parser = "builtin"
# ------------------

# Picker, based on `arg-picker`, a lightweight and type-safe argument parser that aligns better with Mingling's paradigm
# ------------------
parser = "picker"
# ------------------

### 3. If you have async requirements, please select an async runtime
#   Hint: You can only enable one of them
# ------------------
# tokio = true
# async_std = true
# ------------------

### 4. If you need flexible management of your program's exit codes, enable this
# ------------------
exit_code = true
# ------------------

### 5. If your project has completion needs, enable this
# ------------------
completion = true
# ------------------

### 6. If you expect the number of commands to be > 20, 
#   enable the compile-time dispatch tree for faster matching
# ------------------
# dispatch_tree = true
# ------------------

### 7. If you want the program to be able to output structured data controlled by flags such as `--json`, enable this
# ------------------
# structural_renderer = true
# ------------------

### Final. All set. 
#   Please run `mling proj-init` in this directory to continue creating the project.
