[[user.input]]
name = "program_name"

[[user.toggle]]
name = "exit_code"

[[user.toggle]]
name = "tokio"

[[user.toggle]]
name = "async_std"

[[user.toggle-mutex]]
mutex = [ "tokio", "async_std" ]
reason = "You can only select one async runtime"

[[user.toggle]]
name = "completion"

[[user.toggle]]
name = "pathf"
default = true

[[user.toggle]]
name = "structural_renderer"

[[user.toggle]]
name = "dispatch_tree"

[[user.toggle]]
name = "use_parser"

[[user.selection]]
name = "parser"
option = [ "clap", "builtin", "picker" ]

[[user.toggle-mutex]]
mutex = [ "clap", "builtin", "picker" ]
reason = "You can only select one argument parser"

[[display]]
name = "ASYNC_STD"
rule = "async_std"

[[display]]
name = "TOKIO"
rule = "tokio"

[[display]]
name = "ASYNC"
rule = "tokio || async_std"

[[display]]
name = "BUILD_TIME"
rule = "completion || pathf"

[[hide-file]]
file = "./build.rs"
rule = "!completion && !pathf"

[[display]]
name = "PARSER_CLAP"
rule = "use_parser && parser == clap"

[[display]]
name = "PARSER_BUILTIN"
rule = "use_parser && parser == builtin"

[[display]]
name = "PARSER_PICKER"
rule = "use_parser && parser == picker"

[[display]]
name = "COMPLETION"
rule = "completion"

[[display]]
name = "STRUCTURAL_RENDERER"
rule = "structural_renderer"

[[display]]
name = "EXIT_CODE"
rule = "exit_code"

[[display]]
name = "DISPATCH_TREE"
rule = "dispatch_tree"

[[display]]
name = "NOT_DISPATCH_TREE"
rule = "!dispatch_tree"

[[display]]
name = "PATHF"
rule = "pathf"
