[[classes]]
name = "command"
description = "Add a command"
template = "classes/command.rs"
output-dir = "src/app/command/"
append-file = "src/app/command.rs"
append-content = "\npub(crate) mod <<<snake_case>>>;"

[[classes]]
name = "external-type-handler"
description = "Add a handler for external types"
template = "classes/external_type_handler.rs"
output-dir = "src/app/external/"
append-file = "src/app/external.rs"
append-content = "\npub(crate) mod <<<snake_case>>>;"

[[classes]]
name = "external-type-renderer"
description = "Add a renderer for external types"
template = "classes/external_type_renderer.rs"
output-dir = "src/app/external/"
append-file = "src/app/external.rs"
append-content = "\npub(crate) mod <<<snake_case>>>;"

[[classes]]
name = "empty-setup"
description = "Add a handler for an extension setup"
template = "classes/empty_setup.rs"
output-dir = "src/app/extension/"
append-file = "src/app/extension.rs"
append-content = "\npub(crate) mod <<<snake_case>>>;"
