[[classes]]
name = "subcommand"
description = "Add a subcommand"
template = "classes/subcommand.rs"
output-dir = "src/command/"

[[classes]]
name = "error"
description = "Add a error"
template = "classes/error.rs"
output-dir = "src/error/"

[[classes]]
name = "setup"
description = "Add a setup"
template = "classes/setup.rs"
output-dir = "src/setup/"

[[classes]]
name = "hook"
description = "Add a hook setup"
template = "classes/hook.rs"
output-dir = "src/hook/"

[[classes]]
name = "resource"
description = "Add a global resource"
template = "classes/resource.rs"
output-dir = "src/resource/"
